# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'appmain.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1261, 727)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.instrumentGroupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.instrumentGroupbox.setMinimumSize(QtCore.QSize(250, 0))
        self.instrumentGroupbox.setMaximumSize(QtCore.QSize(320, 16777215))
        self.instrumentGroupbox.setObjectName("instrumentGroupbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.instrumentGroupbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.instrumentsLayout = QtWidgets.QVBoxLayout()
        self.instrumentsLayout.setObjectName("instrumentsLayout")
        self.verticalLayout.addLayout(self.instrumentsLayout)
        self.horizontalLayout.addWidget(self.instrumentGroupbox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_2)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.plotsLayout = QtWidgets.QVBoxLayout()
        self.plotsLayout.setObjectName("plotsLayout")
        self.horizontalLayout_2.addLayout(self.plotsLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.hedgeLayout = QtWidgets.QVBoxLayout()
        self.hedgeLayout.setObjectName("hedgeLayout")
        self.horizontalLayout_3.addLayout(self.hedgeLayout)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.horizontalLayout.addWidget(self.groupBox_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1261, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.instrumentGroupbox.setTitle(_translate("MainWindow", "Instrument Configuration"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Data Viz"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
